### ISSUE TITLE
UART Connection

### ISSUE THREAD

**Issue by irqnet** [ProfDrYoMan/tibber_pulse_local_esphome#1]
Polling the tibber pulse localy sounds very interessting, but I didn't get the part with the GPIO UART connection.

Where do I have to connect the pins to?

Pulse to ESP8266 ?

**Comment by ProfDrYoMan** [comment]
Sorry for the late answer.

You need to connect UART TX with UART RX on the same ESP.

This implementations uses the existing UART input parsing of the SML parser and simply generates TX data on the UART polling the pulse via web.
